name: Build
on: 
  push:
    branches:
      - main
      - tmp-*
    tags:
      - v*
  pull_request:

jobs:
  squatter:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: make install
      - name: Test
        run: make test
      - name: Lint
        run: make lint
